export const PALETTE = [
  {
    category: "networking",
    label: "Networking",
    components: [
      { type: "vpc",               label: "VPC",               icon: "🌐", awsType: "VPC" },
      { type: "subnet",            label: "Subnet",            icon: "🔲", awsType: "Subnet" },
      { type: "internet_gateway",  label: "Internet GW",       icon: "🌍", awsType: "Internet Gateway" },
      { type: "nat_gateway",       label: "NAT Gateway",       icon: "🔀", awsType: "NAT Gateway" },
      { type: "route_table",       label: "Route Table",       icon: "🗺️", awsType: "Route Table" },
      { type: "elastic_ip",        label: "Elastic IP",        icon: "📌", awsType: "Elastic IP" },
      { type: "cloudfront",        label: "CloudFront",        icon: "☁️", awsType: "CloudFront" },
      { type: "route53",           label: "Route 53",          icon: "🌏", awsType: "Route 53" },
      { type: "transit_gateway",   label: "Transit Gateway",   icon: "🔗", awsType: "Transit Gateway" },
      { type: "vpn_gateway",       label: "VPN Gateway",       icon: "🔒", awsType: "VPN Gateway" },
      { type: "direct_connect",    label: "Direct Connect",    icon: "🔌", awsType: "Direct Connect" },
      { type: "vpc_endpoint",      label: "VPC Endpoint",      icon: "🎯", awsType: "VPC Endpoint" },
      { type: "global_accelerator",label: "Global Accelerator",icon: "⚡", awsType: "Global Accelerator" },
      { type: "waf",               label: "WAF",               icon: "🔒", awsType: "AWS WAF" },
    ],
  },
  {
    category: "compute",
    label: "Compute",
    components: [
      { type: "ec2",               label: "EC2",               icon: "🖥️", awsType: "EC2" },
      { type: "lambda",            label: "Lambda",            icon: "λ",  awsType: "Lambda" },
      { type: "auto_scaling_group",label: "Auto Scaling",      icon: "⚖️", awsType: "Auto Scaling Group" },
      { type: "ecs_fargate",       label: "ECS / Fargate",     icon: "🐳", awsType: "ECS / Fargate" },
      { type: "eks",               label: "EKS",               icon: "☸️", awsType: "EKS" },
      { type: "elastic_beanstalk", label: "Elastic Beanstalk", icon: "🌱", awsType: "Elastic Beanstalk" },
      { type: "app_runner",        label: "App Runner",        icon: "🏃", awsType: "App Runner" },
      { type: "batch",             label: "AWS Batch",         icon: "📦", awsType: "AWS Batch" },
      { type: "ecr",               label: "ECR",               icon: "🗂️", awsType: "ECR" },
      { type: "lightsail",         label: "Lightsail",         icon: "💡", awsType: "Lightsail" },
    ],
  },
  {
    category: "load_balancing",
    label: "Load Balancing",
    components: [
      { type: "alb",         label: "App Load Balancer", icon: "⚡", awsType: "ALB" },
      { type: "nlb",         label: "Net Load Balancer", icon: "🔌", awsType: "NLB" },
      { type: "api_gateway", label: "API Gateway",       icon: "🚪", awsType: "API Gateway" },
    ],
  },
  {
    category: "storage",
    label: "Storage",
    components: [
      { type: "s3",              label: "S3",              icon: "🪣", awsType: "S3" },
      { type: "ebs",             label: "EBS",             icon: "💾", awsType: "EBS" },
      { type: "efs",             label: "EFS",             icon: "📁", awsType: "EFS" },
      { type: "fsx",             label: "FSx",             icon: "💽", awsType: "Amazon FSx" },
      { type: "s3_glacier",      label: "S3 Glacier",      icon: "🧊", awsType: "S3 Glacier" },
      { type: "backup",          label: "AWS Backup",      icon: "🔄", awsType: "AWS Backup" },
      { type: "storage_gateway", label: "Storage Gateway", icon: "🔗", awsType: "Storage Gateway" },
    ],
  },
  {
    category: "database",
    label: "Database",
    components: [
      { type: "rds",         label: "RDS",         icon: "🗄️", awsType: "RDS" },
      { type: "aurora",      label: "Aurora",      icon: "✨", awsType: "Amazon Aurora" },
      { type: "dynamodb",    label: "DynamoDB",    icon: "⚡", awsType: "DynamoDB" },
      { type: "elasticache", label: "ElastiCache", icon: "🚀", awsType: "ElastiCache" },
      { type: "redshift",    label: "Redshift",    icon: "📊", awsType: "Amazon Redshift" },
      { type: "documentdb",  label: "DocumentDB",  icon: "📄", awsType: "DocumentDB" },
      { type: "neptune",     label: "Neptune",     icon: "🔵", awsType: "Amazon Neptune" },
      { type: "opensearch",  label: "OpenSearch",  icon: "🔍", awsType: "OpenSearch Service" },
      { type: "timestream",  label: "Timestream",  icon: "⏱️", awsType: "Amazon Timestream" },
    ],
  },
  {
    category: "security",
    label: "Security",
    components: [
      { type: "security_group",  label: "Security Group",  icon: "🛡️", awsType: "Security Group" },
      { type: "iam_role",        label: "IAM Role",        icon: "🔑", awsType: "IAM Role" },
      { type: "kms_key",         label: "KMS Key",         icon: "🔐", awsType: "KMS Key" },
      { type: "acm",             label: "ACM Certificate", icon: "📜", awsType: "ACM" },
      { type: "cognito",         label: "Cognito",         icon: "👤", awsType: "Cognito" },
      { type: "secretsmanager",  label: "Secrets Manager", icon: "🗝️", awsType: "Secrets Manager" },
      { type: "guardduty",       label: "GuardDuty",       icon: "👁️", awsType: "Amazon GuardDuty" },
      { type: "cloudtrail",      label: "CloudTrail",      icon: "📝", awsType: "AWS CloudTrail" },
      { type: "inspector",       label: "Inspector",       icon: "🔎", awsType: "Amazon Inspector" },
      { type: "security_hub",    label: "Security Hub",    icon: "🏰", awsType: "Security Hub" },
      { type: "shield",          label: "Shield",          icon: "🛡️", awsType: "AWS Shield" },
      { type: "macie",           label: "Macie",           icon: "🔍", awsType: "Amazon Macie" },
    ],
  },
  {
    category: "integration",
    label: "Integration",
    components: [
      { type: "sns",            label: "SNS",            icon: "📣", awsType: "SNS" },
      { type: "sqs",            label: "SQS",            icon: "📬", awsType: "SQS" },
      { type: "eventbridge",    label: "EventBridge",    icon: "🌉", awsType: "EventBridge" },
      { type: "step_functions", label: "Step Functions", icon: "🔄", awsType: "Step Functions" },
      { type: "kinesis",        label: "Kinesis",        icon: "🌊", awsType: "Kinesis" },
      { type: "mq",             label: "Amazon MQ",      icon: "✉️", awsType: "Amazon MQ" },
      { type: "appsync",        label: "AppSync",        icon: "🔁", awsType: "AWS AppSync" },
    ],
  },
  {
    category: "analytics",
    label: "Analytics",
    components: [
      { type: "glue",            label: "AWS Glue",        icon: "🧩", awsType: "AWS Glue" },
      { type: "athena",          label: "Athena",          icon: "🔍", awsType: "Amazon Athena" },
      { type: "emr",             label: "EMR",             icon: "⚡", awsType: "Amazon EMR" },
      { type: "quicksight",      label: "QuickSight",      icon: "📈", awsType: "QuickSight" },
      { type: "lakeformation",   label: "Lake Formation",  icon: "💧", awsType: "Lake Formation" },
      { type: "msk",             label: "MSK (Kafka)",     icon: "🌊", awsType: "Amazon MSK" },
      { type: "kinesis_firehose",label: "Kinesis Firehose",icon: "🔥", awsType: "Kinesis Firehose" },
    ],
  },
  {
    category: "ai_ml",
    label: "AI / ML",
    components: [
      { type: "sagemaker",   label: "SageMaker",  icon: "🤖", awsType: "SageMaker" },
      { type: "bedrock",     label: "Bedrock",    icon: "🪨", awsType: "Amazon Bedrock" },
      { type: "rekognition", label: "Rekognition",icon: "👁️", awsType: "Rekognition" },
      { type: "comprehend",  label: "Comprehend", icon: "📖", awsType: "Comprehend" },
      { type: "textract",    label: "Textract",   icon: "📄", awsType: "Textract" },
      { type: "polly",       label: "Polly",      icon: "🔊", awsType: "Amazon Polly" },
      { type: "translate",   label: "Translate",  icon: "🌐", awsType: "Amazon Translate" },
      { type: "lex",         label: "Lex",        icon: "💬", awsType: "Amazon Lex" },
    ],
  },
  {
    category: "monitoring",
    label: "Monitoring",
    components: [
      { type: "cloudwatch",     label: "CloudWatch",     icon: "📊", awsType: "CloudWatch" },
      { type: "xray",           label: "X-Ray",          icon: "🔬", awsType: "AWS X-Ray" },
      { type: "systems_manager",label: "Systems Manager",icon: "🔧", awsType: "Systems Manager" },
      { type: "config",         label: "AWS Config",     icon: "📋", awsType: "AWS Config" },
    ],
  },
  {
    category: "devops",
    label: "DevOps",
    components: [
      { type: "codepipeline",   label: "CodePipeline",  icon: "🔄", awsType: "CodePipeline" },
      { type: "codebuild",      label: "CodeBuild",     icon: "🔨", awsType: "CodeBuild" },
      { type: "codedeploy",     label: "CodeDeploy",    icon: "🚀", awsType: "CodeDeploy" },
      { type: "codecommit",     label: "CodeCommit",    icon: "📝", awsType: "CodeCommit" },
      { type: "cloudformation", label: "CloudFormation",icon: "☁️", awsType: "CloudFormation" },
    ],
  },
];
