"""
azurerm resource type → Archon Azure canvas type mapping for TF plan parsing.

Derived from backend/app/services/azure_prompt_builder.py _AZURE_RESOURCE_MAP
(primary + companion resources).
"""

from __future__ import annotations

AZURE_TF_TYPE_MAP: dict[str, str] = {
    # ── Networking ────────────────────────────────────────────────────────────
    "azurerm_virtual_network": "azure_vnet",
    "azurerm_subnet": "azure_subnet",
    "azurerm_subnet_network_security_group_association": "azure_subnet",
    "azurerm_subnet_route_table_association": "azure_subnet",
    "azurerm_subnet_nat_gateway_association": "azure_nat_gw",
    "azurerm_network_security_group": "azure_nsg",
    "azurerm_network_security_rule": "azure_nsg",
    "azurerm_network_interface": "azure_vm",
    "azurerm_network_interface_security_group_association": "azure_vm",
    "azurerm_network_interface_backend_address_pool_association": "azure_vmss",
    "azurerm_public_ip": "azure_lb",
    "azurerm_public_ip_prefix": "azure_lb",
    "azurerm_application_gateway": "azure_agw",
    "azurerm_lb": "azure_lb",
    "azurerm_lb_backend_address_pool": "azure_lb",
    "azurerm_lb_probe": "azure_lb",
    "azurerm_lb_rule": "azure_lb",
    "azurerm_lb_nat_rule": "azure_lb",
    "azurerm_lb_outbound_rule": "azure_lb",
    "azurerm_cdn_frontdoor_profile": "azure_frontdoor",
    "azurerm_cdn_frontdoor_endpoint": "azure_frontdoor",
    "azurerm_cdn_frontdoor_origin_group": "azure_frontdoor",
    "azurerm_cdn_frontdoor_origin": "azure_frontdoor",
    "azurerm_cdn_frontdoor_route": "azure_frontdoor",
    "azurerm_cdn_frontdoor_security_policy": "azure_frontdoor",
    "azurerm_dns_zone": "azure_dns",
    "azurerm_dns_a_record": "azure_dns",
    "azurerm_dns_aaaa_record": "azure_dns",
    "azurerm_dns_cname_record": "azure_dns",
    "azurerm_private_dns_zone": "azure_dns",
    "azurerm_private_dns_a_record": "azure_dns",
    "azurerm_private_dns_zone_virtual_network_link": "azure_dns",
    "azurerm_nat_gateway": "azure_nat_gw",
    "azurerm_nat_gateway_public_ip_association": "azure_nat_gw",
    "azurerm_virtual_network_gateway": "azure_vpn_gateway",
    "azurerm_virtual_network_gateway_connection": "azure_vpn_gateway",
    "azurerm_local_network_gateway": "azure_vpn_gateway",
    "azurerm_express_route_circuit": "azure_expressroute",
    "azurerm_express_route_circuit_peering": "azure_expressroute",
    "azurerm_traffic_manager_profile": "azure_traffic_mgr",
    "azurerm_traffic_manager_azure_endpoint": "azure_traffic_mgr",
    "azurerm_traffic_manager_external_endpoint": "azure_traffic_mgr",
    "azurerm_bastion_host": "azure_bastion",
    "azurerm_private_endpoint": "azure_private_endpoint",
    "azurerm_private_endpoint_connection": "azure_private_endpoint",
    "azurerm_firewall": "azure_firewall",
    "azurerm_firewall_network_rule_collection": "azure_firewall",
    "azurerm_firewall_application_rule_collection": "azure_firewall",
    "azurerm_firewall_policy": "azure_firewall",
    "azurerm_network_ddos_protection_plan": "azure_ddos",
    "azurerm_route_table": "azure_subnet",
    "azurerm_route": "azure_subnet",
    "azurerm_web_application_firewall_policy": "azure_waf",
    "azurerm_frontdoor": "azure_frontdoor",
    "azurerm_frontdoor_firewall_policy": "azure_waf",

    # ── Compute ───────────────────────────────────────────────────────────────
    "azurerm_linux_virtual_machine": "azure_vm",
    "azurerm_windows_virtual_machine": "azure_vm",
    "azurerm_virtual_machine_extension": "azure_vm",
    "azurerm_linux_virtual_machine_scale_set": "azure_vmss",
    "azurerm_windows_virtual_machine_scale_set": "azure_vmss",
    "azurerm_kubernetes_cluster": "azure_aks",
    "azurerm_kubernetes_cluster_node_pool": "azure_aks",
    "azurerm_linux_function_app": "azure_functions",
    "azurerm_windows_function_app": "azure_functions",
    "azurerm_function_app": "azure_functions",
    "azurerm_function_app_function": "azure_functions",
    "azurerm_service_plan": "azure_app_service",
    "azurerm_linux_web_app": "azure_app_service",
    "azurerm_windows_web_app": "azure_app_service",
    "azurerm_app_service": "azure_app_service",
    "azurerm_app_service_plan": "azure_app_service",
    "azurerm_container_group": "azure_aci",
    "azurerm_container_app": "azure_container_apps",
    "azurerm_container_app_environment": "azure_container_apps",
    "azurerm_container_app_environment_storage": "azure_container_apps",
    "azurerm_batch_account": "azure_batch",
    "azurerm_batch_pool": "azure_batch",
    "azurerm_batch_certificate": "azure_batch",
    "azurerm_spring_cloud_service": "azure_spring_apps",
    "azurerm_spring_cloud_app": "azure_spring_apps",
    "azurerm_spring_cloud_java_deployment": "azure_spring_apps",
    "azurerm_static_site": "azure_static_web",
    "azurerm_static_web_app": "azure_static_web",
    "azurerm_container_registry": "azure_acr",
    "azurerm_container_registry_scope_map": "azure_acr",
    "azurerm_container_registry_token": "azure_acr",

    # ── Storage ───────────────────────────────────────────────────────────────
    "azurerm_storage_account": "azure_blob",
    "azurerm_storage_container": "azure_blob",
    "azurerm_storage_blob": "azure_blob",
    "azurerm_storage_share": "azure_files",
    "azurerm_storage_table": "azure_table",
    "azurerm_storage_queue": "azure_queue",
    "azurerm_storage_data_lake_gen2_filesystem": "azure_datalake",
    "azurerm_storage_management_policy": "azure_blob",
    "azurerm_managed_disk": "azure_disk",
    "azurerm_virtual_machine_data_disk_attachment": "azure_disk",
    "azurerm_recovery_services_vault": "azure_backup",
    "azurerm_backup_policy_vm": "azure_backup",
    "azurerm_backup_protected_vm": "azure_backup",

    # ── Database ──────────────────────────────────────────────────────────────
    "azurerm_mssql_server": "azure_sql",
    "azurerm_mssql_database": "azure_sql",
    "azurerm_mssql_server_extended_auditing_policy": "azure_sql",
    "azurerm_mssql_firewall_rule": "azure_sql",
    "azurerm_mssql_virtual_network_rule": "azure_sql",
    "azurerm_mssql_managed_instance": "azure_managed_instance",
    "azurerm_mssql_managed_database": "azure_managed_instance",
    "azurerm_cosmosdb_account": "azure_cosmosdb",
    "azurerm_cosmosdb_sql_database": "azure_cosmosdb",
    "azurerm_cosmosdb_sql_container": "azure_cosmosdb",
    "azurerm_cosmosdb_mongo_database": "azure_cosmosdb",
    "azurerm_cosmosdb_mongo_collection": "azure_cosmosdb",
    "azurerm_redis_cache": "azure_redis",
    "azurerm_redis_firewall_rule": "azure_redis",
    "azurerm_postgresql_flexible_server": "azure_postgres",
    "azurerm_postgresql_flexible_server_database": "azure_postgres",
    "azurerm_postgresql_flexible_server_firewall_rule": "azure_postgres",
    "azurerm_postgresql_flexible_server_configuration": "azure_postgres",
    "azurerm_mysql_flexible_server": "azure_mysql",
    "azurerm_mysql_flexible_database": "azure_mysql",
    "azurerm_mysql_flexible_server_firewall_rule": "azure_mysql",
    "azurerm_mariadb_server": "azure_mariadb",
    "azurerm_mariadb_database": "azure_mariadb",
    "azurerm_mariadb_firewall_rule": "azure_mariadb",
    "azurerm_synapse_workspace": "azure_synapse",
    "azurerm_synapse_sql_pool": "azure_synapse",
    "azurerm_synapse_spark_pool": "azure_synapse",

    # ── Security ──────────────────────────────────────────────────────────────
    "azurerm_key_vault": "azure_keyvault",
    "azurerm_key_vault_access_policy": "azure_keyvault",
    "azurerm_key_vault_key": "azure_keyvault",
    "azurerm_key_vault_secret": "azure_keyvault",
    "azurerm_key_vault_certificate": "azure_keyvault",
    "azurerm_user_assigned_identity": "azure_managed_id",
    "azurerm_role_assignment": "azure_aad",
    "azurerm_role_definition": "azure_policy",
    "azurerm_policy_definition": "azure_policy",
    "azurerm_policy_assignment": "azure_policy",
    "azurerm_policy_set_definition": "azure_policy",
    "azurerm_security_center_subscription_pricing": "azure_defender",
    "azurerm_security_center_contact": "azure_defender",
    "azurerm_security_center_auto_provisioning": "azure_defender",
    "azurerm_sentinel_log_analytics_workspace_onboarding": "azure_sentinel",
    "azurerm_sentinel_alert_rule_scheduled": "azure_sentinel",
    "azurerm_sentinel_data_connector_azure_active_directory": "azure_sentinel",

    # ── Integration ───────────────────────────────────────────────────────────
    "azurerm_servicebus_namespace": "azure_servicebus",
    "azurerm_servicebus_queue": "azure_servicebus",
    "azurerm_servicebus_topic": "azure_servicebus",
    "azurerm_servicebus_subscription": "azure_servicebus",
    "azurerm_servicebus_namespace_authorization_rule": "azure_servicebus",
    "azurerm_eventhub_namespace": "azure_eventhub",
    "azurerm_eventhub": "azure_eventhub",
    "azurerm_eventhub_authorization_rule": "azure_eventhub",
    "azurerm_eventhub_consumer_group": "azure_eventhub",
    "azurerm_logic_app_workflow": "azure_logicapp",
    "azurerm_logic_app_trigger_http_request": "azure_logicapp",
    "azurerm_logic_app_action_http": "azure_logicapp",
    "azurerm_api_management": "azure_apim",
    "azurerm_api_management_api": "azure_apim",
    "azurerm_api_management_product": "azure_apim",
    "azurerm_signalr_service": "azure_signalr",
    "azurerm_notification_hub_namespace": "azure_notification_hub",
    "azurerm_notification_hub": "azure_notification_hub",

    # ── Analytics ─────────────────────────────────────────────────────────────
    "azurerm_data_factory": "azure_datafactory",
    "azurerm_data_factory_linked_service_azure_blob_storage": "azure_datafactory",
    "azurerm_data_factory_pipeline": "azure_datafactory",
    "azurerm_stream_analytics_job": "azure_stream_analytics",
    "azurerm_stream_analytics_stream_input_eventhub": "azure_stream_analytics",
    "azurerm_stream_analytics_output_blob": "azure_stream_analytics",
    "azurerm_databricks_workspace": "azure_databricks",
    "azurerm_databricks_access_connector": "azure_databricks",
    "azurerm_hdinsight_hadoop_cluster": "azure_hdinsight",
    "azurerm_hdinsight_kafka_cluster": "azure_hdinsight",
    "azurerm_purview_account": "azure_purview",

    # ── AI / ML ───────────────────────────────────────────────────────────────
    "azurerm_cognitive_account": "azure_cognitive",
    "azurerm_cognitive_deployment": "azure_openai",
    "azurerm_machine_learning_workspace": "azure_ml",
    "azurerm_machine_learning_compute_cluster": "azure_ml",
    "azurerm_bot_channels_registration": "azure_bot",
    "azurerm_bot_channel_ms_teams": "azure_bot",
    "azurerm_bot_channel_slack": "azure_bot",
    "azurerm_search_service": "azure_search",

    # ── Monitoring ────────────────────────────────────────────────────────────
    "azurerm_monitor_action_group": "azure_monitor",
    "azurerm_monitor_metric_alert": "azure_monitor",
    "azurerm_monitor_activity_log_alert": "azure_monitor",
    "azurerm_monitor_diagnostic_setting": "azure_monitor",
    "azurerm_application_insights": "azure_app_insights",
    "azurerm_application_insights_web_test": "azure_app_insights",
    "azurerm_log_analytics_workspace": "azure_log_analytics",
    "azurerm_log_analytics_solution": "azure_log_analytics",

    # ── Shared / platform ───────────────────────────────────────────────────────
    "azurerm_resource_group": "azure_vnet",
    "azurerm_management_lock": "azure_policy",
    "azurerm_monitor_autoscale_setting": "azure_vmss",
}
