/**
 * Comprehensive Azure component reference data for the Academy Library.
 * Same shape as awsComponentLibrary.js.
 */

export const CATEGORIES = {
  networking:  "Networking",
  compute:     "Compute",
  storage:     "Storage & Database",
  security:    "Security & Identity",
  appServices: "App Services",
  monitoring:  "Monitoring & Ops",
};

export const AZURE_COMPONENTS = [
  // ── NETWORKING ───────────────────────────────────────────────────────────────
  {
    id: "azure_vnet",
    name: "Virtual Network (VNet)",
    category: "networking",
    icon: "🌐",
    shortDescription: "Your private, isolated network within Azure — the foundation of every Azure architecture.",
    description:
      "An Azure Virtual Network (VNet) is the fundamental building block of your private network in Azure. It lets Azure resources — VMs, databases, App Services — communicate securely with each other, the internet, and on-premises networks. You define an address space (CIDR block), divide it into subnets, and control traffic with Network Security Groups and route tables. VNets are region-scoped; use VNet Peering or a hub-spoke topology to connect across regions.",
    whenToUse: [
      "Every production Azure architecture — always deploy into a VNet",
      "When you need network isolation between environments (dev, staging, prod)",
      "When connecting on-premises networks via VPN Gateway or ExpressRoute",
      "When PaaS services should be reachable only within your VNet via Private Endpoints",
    ],
    commonMistakes: [
      "Using an address space that overlaps with on-premises networks, breaking peering",
      "Forgetting VNets are regional — you need VNet Peering for cross-region connectivity",
      "Lumping all resources into a single subnet instead of separating web, app, and data tiers",
      "Not planning address space carefully — expanding a live VNet is painful",
    ],
    typicalConnections: ["azure_subnet", "azure_nsg", "azure_vpn_gateway", "azure_load_balancer"],
    pricingModel: "VNets are free. You pay for VPN Gateways, NAT Gateways, and data transfer.",
    freeTier: true,
    docUrl: "https://learn.microsoft.com/en-us/azure/virtual-network/virtual-networks-overview",
  },
  {
    id: "azure_subnet",
    name: "Subnet",
    category: "networking",
    icon: "🔲",
    shortDescription: "A segment of a VNet's IP space — used to isolate and group resources by tier.",
    description:
      "Subnets divide a VNet's address space and let you apply different NSG and routing policies to each tier. A web subnet allows HTTP/HTTPS from the internet; a data subnet allows only traffic from the app subnet. Azure reserves 5 addresses per subnet (network, broadcast, and three Azure internal), so factor that into CIDR sizing. Dedicated subnets are required for Application Gateway, VPN Gateway (must be named 'GatewaySubnet'), and Azure Bastion.",
    whenToUse: [
      "Web tier: public-facing load balancers and App Service Environments",
      "App tier: internal application servers not directly internet-accessible",
      "Data tier: databases locked to only accept traffic from the app subnet",
      "Gateway subnet: dedicated /27 or larger for VPN Gateway or ExpressRoute",
    ],
    commonMistakes: [
      "Using /29 subnets and running out of IPs after Azure's 5-address reservation",
      "Not naming the VPN Gateway subnet exactly 'GatewaySubnet'",
      "Sharing the Application Gateway subnet with other resources — it needs a dedicated subnet",
      "Using the same NSG for every subnet — each tier should have purpose-built rules",
    ],
    typicalConnections: ["azure_vnet", "azure_vm", "azure_nsg", "azure_sql_database"],
    pricingModel: "Free.",
    freeTier: true,
    docUrl: "https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-manage-subnet",
  },
  {
    id: "azure_nsg",
    name: "Network Security Group",
    category: "networking",
    icon: "🛡️",
    shortDescription: "Stateful firewall rules that filter inbound and outbound traffic at the subnet or NIC level.",
    description:
      "An NSG contains priority-ordered rules that allow or deny traffic by protocol, port, and source/destination (IP, CIDR, or Service Tag). NSGs are stateful — allowing inbound automatically allows the response outbound. They can be applied to subnets (all resources) or individual NICs. Service Tags like 'Internet', 'AzureLoadBalancer', and 'VirtualNetwork' abstract away IP ranges that change over time. Azure provides default rules that you can override but not delete.",
    whenToUse: [
      "Every subnet should have an NSG — it is the primary network defence layer",
      "Allow only HTTP/HTTPS (80/443) from Internet to the web subnet",
      "Allow the app subnet to reach the data subnet on DB ports only",
      "Deny all direct internet access to data-tier resources",
    ],
    commonMistakes: [
      "Not enabling NSG flow logs — you lose network-level visibility for troubleshooting",
      "Using IP addresses in rules instead of Service Tags — IPs change, tags are maintained by Azure",
      "Leaving the default 'AllowVnetInBound' rule without verifying its scope for your architecture",
      "Applying overly broad rules during development and forgetting to tighten before production",
    ],
    typicalConnections: ["azure_subnet", "azure_vm", "azure_load_balancer"],
    pricingModel: "NSGs are free. Flow log storage has a small cost.",
    freeTier: true,
    docUrl: "https://learn.microsoft.com/en-us/azure/virtual-network/network-security-groups-overview",
  },
  {
    id: "azure_load_balancer",
    name: "Load Balancer",
    category: "networking",
    icon: "⚖️",
    shortDescription: "Layer 4 (TCP/UDP) traffic distribution across a pool of backend VMs.",
    description:
      "Azure Load Balancer operates at Layer 4 and distributes TCP/UDP traffic across VMs or Scale Set instances. The Standard SKU is zone-redundant, supports HA ports, and has an SLA. Use it for non-HTTP protocols, high-throughput TCP workloads, or internal load balancing between tiers. For HTTP/HTTPS with path routing, SSL offloading, and WAF, use Application Gateway instead. Standard Load Balancer blocks all inbound traffic by default — you must have an NSG to allow it.",
    whenToUse: [
      "Distributing TCP/UDP traffic (non-HTTP) across multiple VMs",
      "Internal load balancing between application tiers inside a VNet",
      "High-availability deployments across Availability Zones",
      "Outbound SNAT connectivity for VMs without public IPs",
    ],
    commonMistakes: [
      "Using Basic SKU for production — no zone redundancy, no SLA, no diagnostics",
      "Choosing Load Balancer for HTTP traffic when Application Gateway with WAF is more appropriate",
      "Misconfiguring health probes — wrong paths or ports cause all backends to go unhealthy",
      "Forgetting Standard Load Balancer requires explicit NSG rules to allow inbound traffic",
    ],
    typicalConnections: ["azure_vm", "azure_vmss", "azure_subnet", "azure_nsg"],
    pricingModel: "Standard: ~$0.005/hour + $0.008/GB processed. Basic: free (no SLA).",
    freeTier: false,
    docUrl: "https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-overview",
  },
  {
    id: "azure_application_gateway",
    name: "Application Gateway",
    category: "networking",
    icon: "🚦",
    shortDescription: "Layer 7 load balancer with URL routing, SSL termination, and integrated WAF.",
    description:
      "Azure Application Gateway routes HTTP/HTTPS requests based on URL path, hostname, or headers. It handles SSL termination, WebSocket connections, cookie-based affinity, HTTP header rewriting, and redirect rules. The WAF (Web Application Firewall) SKU adds OWASP CRS rule sets, custom rules, and bot protection. Application Gateway v2 is autoscaling and zone-redundant. It is the standard front-door for web applications and containerised workloads on AKS.",
    whenToUse: [
      "Path-based routing: /api/* to one backend pool, /* to another",
      "Multi-site hosting: multiple domains on a single gateway",
      "WAF protection for public-facing web applications",
      "SSL offloading — terminate HTTPS at the gateway, use HTTP internally",
    ],
    commonMistakes: [
      "Deploying into a subnet shared with other resources — Application Gateway needs a dedicated subnet",
      "Using v1 SKU — v2 has autoscaling, zone redundancy, and better performance",
      "Not enabling WAF for public-facing apps — it's the primary OWASP Top 10 protection",
      "Misconfiguring health probes that return a redirect (301) — the gateway marks backends unhealthy",
    ],
    typicalConnections: ["azure_vm", "azure_vmss", "azure_aks", "azure_app_service", "azure_subnet"],
    pricingModel: "WAF v2: ~$0.246/hour + capacity units. Standard v2: ~$0.246/hour.",
    freeTier: false,
    docUrl: "https://learn.microsoft.com/en-us/azure/application-gateway/overview",
  },
  {
    id: "azure_dns",
    name: "Azure DNS",
    category: "networking",
    icon: "🌍",
    shortDescription: "Host DNS zones and resolve domain names using Microsoft's global DNS infrastructure.",
    description:
      "Azure DNS hosts your DNS zones using Microsoft's anycast network of name servers globally. It supports all standard record types and Alias records that automatically track the changing IPs of Azure resources. Private DNS zones provide name resolution within a VNet without a custom DNS server, enabling Azure PaaS services connected via Private Endpoint to resolve by name. Split-horizon DNS lets the same domain resolve differently inside and outside the VNet.",
    whenToUse: [
      "Hosting a custom domain that points to Azure Load Balancers or App Services",
      "Private DNS zones for VNet-internal resolution (Private Endpoint name resolution)",
      "Alias records to automatically track changing public IPs and Traffic Manager profiles",
      "Split-horizon: same domain, different answers inside and outside your VNet",
    ],
    commonMistakes: [
      "Using CNAME at the zone apex — use Alias records instead for the root domain",
      "Forgetting to link a Private DNS zone to the VNet — records only resolve if the zone is VNet-linked",
      "Setting TTLs too high during a migration — propagation can't happen faster than the TTL",
      "Mixing Azure DNS and an external provider without proper zone delegation",
    ],
    typicalConnections: ["azure_vnet", "azure_load_balancer", "azure_application_gateway"],
    pricingModel: "$0.90/zone/month + $0.40/million queries.",
    freeTier: false,
    docUrl: "https://learn.microsoft.com/en-us/azure/dns/dns-overview",
  },

  // ── COMPUTE ──────────────────────────────────────────────────────────────────
  {
    id: "azure_vm",
    name: "Virtual Machine",
    category: "compute",
    icon: "🖥️",
    shortDescription: "On-demand virtual servers — Windows or Linux, any size, full OS control.",
    description:
      "Azure Virtual Machines provide flexible, on-demand compute without purchasing hardware. You choose the OS, VM series (D-series general purpose, E-series memory, F-series compute, N-series GPU), managed disk, and VNet subnet. Managed Disks handle redundancy automatically. Without an Availability Set or Zone, a single VM has no uptime SLA. Managed Identities allow a VM to authenticate to Azure services without credentials in code.",
    whenToUse: [
      "Lift-and-shift migrations of on-premises workloads to Azure",
      "Workloads requiring full OS control, specific kernel, or licensed software",
      "App servers in a traditional 3-tier architecture behind a load balancer",
      "When PaaS services don't meet your control or compliance requirements",
    ],
    commonMistakes: [
      "Using unmanaged disks — Managed Disks handle redundancy and simplify snapshots",
      "Storing data on the temporary disk (D: drive) — it is ephemeral and lost on reboot",
      "Deploying a single VM in no Availability Set or Zone — no HA guarantee",
      "Not assigning a Managed Identity — results in secrets or service principal credentials in code",
    ],
    typicalConnections: ["azure_subnet", "azure_nsg", "azure_load_balancer", "azure_sql_database", "azure_key_vault"],
    pricingModel: "Per-second billing. B1ls ~$0.008/hr to hundreds for GPU. Reserved saves up to 72%.",
    freeTier: true,
    docUrl: "https://learn.microsoft.com/en-us/azure/virtual-machines/overview",
  },
  {
    id: "azure_vmss",
    name: "VM Scale Sets",
    category: "compute",
    icon: "📈",
    shortDescription: "Automatically scale identical VMs in/out based on demand or schedule.",
    description:
      "Azure Virtual Machine Scale Sets (VMSS) manage a group of identical, load-balanced VMs. The cluster autoscaler adjusts count based on CPU, memory, or custom metrics. Flexible orchestration mode supports Availability Zone distribution for zone-redundancy. VMSS is the foundation for stateless web/app tiers that must handle variable load without manual intervention. All VMs in a set share the same base image and configuration, ensuring consistency.",
    whenToUse: [
      "Stateless web or application servers with variable traffic",
      "Batch processing where you scale workers up for a job and back down after",
      "High-availability deployments across Availability Zones",
      "Any EC2-style workload that needs autoscaling and instance replacement",
    ],
    commonMistakes: [
      "Using a slow-to-boot custom image — scale-out during a spike takes too long",
      "Not pairing with a load balancer — new instances don't receive traffic",
      "Setting scale-in policy incorrectly for apps that need drain time",
      "Not testing scale-in — apps must handle instance termination gracefully",
    ],
    typicalConnections: ["azure_load_balancer", "azure_application_gateway", "azure_subnet", "azure_nsg"],
    pricingModel: "No charge for VMSS itself. You pay for the VMs it manages.",
    freeTier: false,
    docUrl: "https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/overview",
  },
  {
    id: "azure_aks",
    name: "AKS (Kubernetes)",
    category: "compute",
    icon: "🐳",
    shortDescription: "Managed Kubernetes — Azure handles the control plane, you run your workloads.",
    description:
      "Azure Kubernetes Service (AKS) provides a managed Kubernetes control plane at no cost — you only pay for the agent node VMs. AKS integrates with Azure AD for RBAC, Azure Container Registry for image pulls, Azure Monitor for container insights, and Azure CNI for pod networking within your VNet. Node pools can use different VM sizes; the cluster autoscaler adjusts node count based on pending pod resource requests. Multiple node pools and Availability Zone support provide production-grade resilience.",
    whenToUse: [
      "Microservices architectures where each service runs as a Kubernetes deployment",
      "Teams already using Kubernetes who want a managed cloud offering",
      "Complex container workloads requiring service mesh, ingress controllers, or advanced networking",
      "CI/CD pipelines deploying containerised applications continuously",
    ],
    commonMistakes: [
      "Using a single node pool in one AZ — no zone redundancy means no node-level SLA",
      "Not enabling the cluster autoscaler — fixed node count can't handle traffic spikes",
      "Pulling images from Docker Hub in production — rate limits cause pod failures; use ACR",
      "Giving pods broad Azure RBAC permissions instead of Workload Identity with minimal scope",
    ],
    typicalConnections: ["azure_application_gateway", "azure_sql_database", "azure_key_vault", "azure_subnet"],
    pricingModel: "Control plane: free. Node VMs: standard VM pricing. Uptime SLA: ~$0.10/cluster/hour (optional).",
    freeTier: false,
    docUrl: "https://learn.microsoft.com/en-us/azure/aks/intro-kubernetes",
  },
  {
    id: "azure_functions",
    name: "Azure Functions",
    category: "compute",
    icon: "⚡",
    shortDescription: "Event-driven serverless compute — run code without managing infrastructure.",
    description:
      "Azure Functions executes code in response to triggers: HTTP, timer, Service Bus, Event Hub, Blob Storage, and more. The Consumption plan scales to zero and charges only for execution time (1 million free invocations/month). Premium plan adds VNet integration, pre-warmed instances (no cold starts), and longer timeouts. Durable Functions enable stateful orchestrations and fan-out/fan-in patterns within the serverless model.",
    whenToUse: [
      "HTTP APIs with infrequent or unpredictable traffic (Consumption scales to zero)",
      "Processing messages from Service Bus or Event Hub",
      "Scheduled background jobs using timer triggers",
      "Orchestrating multi-step workflows with Durable Functions",
    ],
    commonMistakes: [
      "Using Consumption plan for latency-sensitive APIs — cold starts can take seconds",
      "Storing state in-memory between invocations — the environment is stateless",
      "Not setting a function timeout — default 5 min on Consumption; use Premium for long-running tasks",
      "Using one Function App for unrelated functions — separate them with different Managed Identities",
    ],
    typicalConnections: ["azure_service_bus", "azure_event_hub", "azure_blob_storage", "azure_cosmos_db", "azure_key_vault"],
    pricingModel: "Consumption: 1M executions/month free, then $0.20/million. 400K GB-seconds free.",
    freeTier: true,
    docUrl: "https://learn.microsoft.com/en-us/azure/azure-functions/functions-overview",
  },
  {
    id: "azure_app_service",
    name: "App Service",
    category: "compute",
    icon: "🌐",
    shortDescription: "Fully managed platform for hosting web apps and REST APIs without managing servers.",
    description:
      "Azure App Service is a PaaS offering for web applications and APIs in .NET, Java, Python, Node.js, PHP, or Ruby. An App Service Plan defines the underlying compute. Deployment slots enable zero-downtime blue/green deployments via a slot swap. VNet Integration provides outbound private connectivity. Easy Auth provides built-in authentication with Azure AD, Google, or GitHub without code changes. Auto-scaling and custom domain TLS are built-in on Standard and above.",
    whenToUse: [
      "Web applications and REST APIs where you don't want to manage servers",
      "Staging environments using deployment slots for zero-downtime swaps",
      "Apps needing built-in auth (Easy Auth) with Azure AD or social providers",
      "Between Functions (fully serverless) and AKS (full container orchestration)",
    ],
    commonMistakes: [
      "Using Free or Shared tier for production — no TLS on custom domains, no SLA",
      "Not using deployment slots — deploying directly to production causes downtime during restarts",
      "Storing secrets in App Settings as plaintext instead of Key Vault references",
      "Putting unrelated apps on one Plan — a spike in one starves the others",
    ],
    typicalConnections: ["azure_sql_database", "azure_redis_cache", "azure_application_gateway", "azure_key_vault"],
    pricingModel: "Basic B1: ~$13/month. Standard S1: ~$73/month. Premium P1v3: ~$138/month.",
    freeTier: true,
    docUrl: "https://learn.microsoft.com/en-us/azure/app-service/overview",
  },

  // ── STORAGE & DATABASE ───────────────────────────────────────────────────────
  {
    id: "azure_blob_storage",
    name: "Blob Storage",
    category: "storage",
    icon: "🪣",
    shortDescription: "Massively scalable object storage for unstructured data — files, images, backups, logs.",
    description:
      "Azure Blob Storage stores unstructured objects in containers within a Storage Account. Hot, Cool, and Archive tiers let you balance access speed against cost. Blob versioning, soft delete, and point-in-time restore protect against accidental deletion. Static website hosting serves SPAs directly. Azure Data Lake Storage Gen2 (ADLS) is Blob Storage with a hierarchical namespace, enabling big data analytics with Synapse and Databricks.",
    whenToUse: [
      "User-uploaded files, images, and videos",
      "Hosting static websites and single-page applications via Azure CDN",
      "Data lake storage for analytics pipelines (Synapse, Databricks)",
      "Backup target for databases and VM disk snapshots",
    ],
    commonMistakes: [
      "Not enabling soft delete and versioning on containers holding critical data",
      "Using Hot tier for infrequently accessed data — Cool is 50% cheaper",
      "Granting anonymous public read access to containers with sensitive data",
      "Not setting Lifecycle Management policies — old blobs accumulate indefinitely",
    ],
    typicalConnections: ["azure_functions", "azure_synapse", "azure_event_hub"],
    pricingModel: "Hot: ~$0.018/GB-month. Cool: ~$0.01/GB-month. Archive: ~$0.001/GB-month.",
    freeTier: true,
    docUrl: "https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction",
  },
  {
    id: "azure_sql_database",
    name: "Azure SQL Database",
    category: "storage",
    icon: "🗄️",
    shortDescription: "Fully managed SQL Server database as a service with built-in HA and automated backups.",
    description:
      "Azure SQL Database is a fully managed relational database built on SQL Server. It handles patching, backups (up to 35-day PITR), high availability (99.99% SLA), and performance tuning automatically. The Serverless compute tier auto-pauses when idle, making it ideal for dev/test. Business Critical tier uses local SSDs for the highest IOPS. Hyperscale can grow to 100TB. It supports Azure AD authentication, eliminating the need for SQL login credentials in applications.",
    whenToUse: [
      "Applications needing a managed relational database with ACID compliance",
      "Migrating SQL Server databases from on-premises (near-full compatibility)",
      "Dev/test databases using the Serverless tier that auto-pauses when unused",
      "High-IOPS transactional workloads on the Business Critical tier",
    ],
    commonMistakes: [
      "Not configuring a firewall rule or Private Endpoint — the DB is inaccessible by default",
      "Using SQL authentication instead of Azure AD authentication for application access",
      "Choosing DTU model when vCore is needed for Serverless or Hyperscale",
      "Not enabling Defender for SQL on production databases",
    ],
    typicalConnections: ["azure_vm", "azure_app_service", "azure_functions", "azure_subnet", "azure_key_vault"],
    pricingModel: "General Purpose: ~$0.0131/vCore/hour. Serverless: $0.000145/vCore-second (billed only active).",
    freeTier: true,
    docUrl: "https://learn.microsoft.com/en-us/azure/azure-sql/database/sql-database-paas-overview",
  },
  {
    id: "azure_cosmos_db",
    name: "Cosmos DB",
    category: "storage",
    icon: "🌌",
    shortDescription: "Globally distributed NoSQL database with single-digit millisecond latency at any scale.",
    description:
      "Azure Cosmos DB is a fully managed, multi-model NoSQL database with APIs for NoSQL (document), MongoDB, Cassandra, Gremlin (graph), and Table. Data is automatically replicated to any number of Azure regions you configure. Consistency levels range from Strong to Eventual. Multi-region writes enable active-active global deployments. Throughput is provisioned in Request Units (RU/s) or set to serverless. The free tier provides 1,000 RU/s and 25GB per account.",
    whenToUse: [
      "Global apps needing low-latency reads and writes from multiple regions",
      "High-throughput IoT telemetry, gaming, and user session stores",
      "Flexible-schema data models that evolve rapidly",
      "Migrating MongoDB workloads to a fully managed service",
    ],
    commonMistakes: [
      "Choosing a low-cardinality partition key — causes hot partitions and throttling",
      "Over-provisioning manual RU/s — use autoscale for variable loads",
      "Treating it like a relational database — joins and complex aggregations don't work well",
      "Not understanding consistency levels — Eventual can serve stale reads",
    ],
    typicalConnections: ["azure_functions", "azure_app_service", "azure_aks", "azure_event_hub"],
    pricingModel: "Serverless: $0.25/million RUs. Provisioned: ~$0.008/100 RU/s/hour. 25GB + 1000 RU/s free.",
    freeTier: true,
    docUrl: "https://learn.microsoft.com/en-us/azure/cosmos-db/introduction",
  },
  {
    id: "azure_redis_cache",
    name: "Azure Cache for Redis",
    category: "storage",
    icon: "🚀",
    shortDescription: "Fully managed Redis — sub-millisecond in-memory cache for any application.",
    description:
      "Azure Cache for Redis provides a managed Redis instance. Use it to cache expensive database query results, store sessions for stateless application servers, implement distributed locks, or power pub/sub real-time features. Basic tier is dev/test only — no SLA or replica. Standard adds replication and SLA. Premium adds geo-replication, VNet injection, persistence, and clustering. Enterprise tier provides Redis Enterprise modules for higher throughput and advanced data structures.",
    whenToUse: [
      "Caching SQL query results to reduce Azure SQL load",
      "Session storage for stateless App Service or AKS workloads",
      "Pub/sub messaging for real-time dashboards or chat",
      "Rate limiting and distributed locking across multiple app instances",
    ],
    commonMistakes: [
      "Using Basic tier for production — no replica, no SLA, data lost on restart",
      "Not setting maxmemory-policy — when memory fills, eviction is unpredictable",
      "Caching without TTL — cache fills with stale data that never expires",
      "Accessing Redis over the public endpoint — use VNet injection or Private Link",
    ],
    typicalConnections: ["azure_app_service", "azure_functions", "azure_aks", "azure_subnet"],
    pricingModel: "C0 Basic: ~$16/month. C1 Standard: ~$100/month. P1 Premium: ~$370/month.",
    freeTier: false,
    docUrl: "https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-overview",
  },
  {
    id: "azure_synapse",
    name: "Azure Synapse Analytics",
    category: "storage",
    icon: "🔬",
    shortDescription: "Unified analytics: data warehousing, big data Spark, and data integration in one workspace.",
    description:
      "Azure Synapse Analytics combines enterprise data warehousing (Dedicated SQL Pool), Apache Spark big data processing, and data integration (Synapse Pipelines) in a single unified workspace. Serverless SQL Pools query data in Azure Data Lake Storage Gen2 without ingesting it, paying per TB scanned. Dedicated SQL Pools scale compute independently from storage. Synapse Link enables near-real-time analytics directly on Cosmos DB operational data without ETL.",
    whenToUse: [
      "Enterprise data warehouse for BI reporting and aggregated analytics",
      "Big data ETL and ML feature engineering using Spark",
      "Ad-hoc SQL queries over a data lake without moving data (serverless SQL)",
      "Modern data lakehouse on top of ADLS Gen2",
    ],
    commonMistakes: [
      "Leaving a Dedicated SQL Pool running when not in use — pause it to stop compute charges",
      "Using Dedicated Pool for small analytical workloads when serverless SQL is cheaper",
      "Not distributing large tables by hash — causes data movement in every query",
      "Mixing OLTP and OLAP workloads — Synapse is for analytics, not transactional use",
    ],
    typicalConnections: ["azure_blob_storage", "azure_cosmos_db", "azure_event_hub"],
    pricingModel: "Serverless SQL: $5/TB scanned. Dedicated: $1.20/DWU100/hour. Spark: per vCore-hour.",
    freeTier: false,
    docUrl: "https://learn.microsoft.com/en-us/azure/synapse-analytics/overview-what-is",
  },

  // ── SECURITY & IDENTITY ───────────────────────────────────────────────────────
  {
    id: "azure_ad",
    name: "Azure AD (Entra ID)",
    category: "security",
    icon: "🏢",
    shortDescription: "Cloud identity platform — authentication, RBAC, SSO, and Managed Identities for Azure.",
    description:
      "Azure Active Directory (Microsoft Entra ID) is the identity and access management backbone of Azure. It authenticates users and applications, authorises resource access via RBAC, and enables SSO. Managed Identities give Azure services an identity without credentials in code — the managed identity is the authentication. Conditional Access enforces MFA and blocks risky sign-ins. Every Azure deployment relies on Azure AD for both user and service-to-service identity.",
    whenToUse: [
      "Every Azure deployment — Azure AD controls all resource access",
      "Replacing service principal secrets with Managed Identities",
      "Enforcing MFA and Conditional Access for admins",
      "SSO for internal applications and Microsoft 365",
    ],
    commonMistakes: [
      "Using service principal secrets instead of Managed Identities — secrets expire and need rotation",
      "Granting broad RBAC roles (Owner, Contributor) instead of least-privilege",
      "Not enabling PIM (Privileged Identity Management) for just-in-time admin access",
      "Ignoring Azure AD sign-in logs — primary source of identity threat detection",
    ],
    typicalConnections: ["azure_vm", "azure_aks", "azure_app_service", "azure_key_vault", "azure_sql_database"],
    pricingModel: "Free tier: basic SSO and MFA. P1: $6/user/month. P2: $9/user/month (adds PIM, Identity Protection).",
    freeTier: true,
    docUrl: "https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-whatis",
  },
  {
    id: "azure_key_vault",
    name: "Key Vault",
    category: "security",
    icon: "🔐",
    shortDescription: "Centralised secrets, encryption keys, and certificate management for Azure applications.",
    description:
      "Azure Key Vault stores secrets (connection strings, API keys), encryption keys, and TLS certificates. Applications retrieve secrets at runtime via the SDK or REST API, keeping values out of code. Managed Identity + Key Vault RBAC eliminates all stored credentials. Soft delete and purge protection prevent accidental or malicious deletion. HSM-backed Premium tier provides FIPS 140-2 Level 2 hardware key protection. Certificate auto-rotation integrates with App Service and Application Gateway.",
    whenToUse: [
      "All application secrets, connection strings, and API keys — never in code or environment variables",
      "TLS certificate management with auto-rotation for App Service and Application Gateway",
      "Encryption key management for Storage, SQL, and Disk Encryption",
      "Centralising secrets so rotation happens in one place across all apps",
    ],
    commonMistakes: [
      "Not enabling soft delete and purge protection — secrets and keys can be permanently lost",
      "Using access policies instead of Azure RBAC — RBAC is more granular and auditable",
      "Caching secrets too aggressively — you'll serve old secrets after rotation",
      "Giving an app vault Owner access instead of only the permissions it needs",
    ],
    typicalConnections: ["azure_vm", "azure_app_service", "azure_functions", "azure_aks", "azure_sql_database"],
    pricingModel: "Standard: $0.03/10K operations. Premium (HSM keys): $1.00/key/month. Certificates: $3/renewal.",
    freeTier: false,
    docUrl: "https://learn.microsoft.com/en-us/azure/key-vault/general/overview",
  },
  {
    id: "azure_firewall",
    name: "Azure Firewall",
    category: "security",
    icon: "🧱",
    shortDescription: "Managed, stateful network firewall with FQDN filtering and threat intelligence.",
    description:
      "Azure Firewall is a managed stateful firewall protecting Azure VNet resources. It filters at Layers 3–7 using application rules (FQDN-based, e.g. allow *.microsoft.com:443), network rules (IP/port), and NAT rules for inbound. Premium adds IDPS, TLS inspection, and URL filtering. Deployed in a hub VNet, it inspects all traffic flowing between spokes and the internet. Firewall Policy enables centrally managed, hierarchical rule sets across multiple firewalls.",
    whenToUse: [
      "Hub-spoke architectures where all outbound internet traffic should be inspected",
      "Centrally controlling which FQDNs app servers can reach on the internet",
      "Blocking outbound traffic to known malicious IPs using Threat Intelligence",
      "Replacing multiple NSGs with fully stateful L7 filtering at a hub",
    ],
    commonMistakes: [
      "Deploying in each spoke instead of a shared hub — defeats the purpose",
      "Not using Firewall Policy — classic rules are harder to manage at scale",
      "Forgetting the subnet must be named exactly 'AzureFirewallSubnet' with /26 minimum",
      "Using Azure Firewall for east-west between small spokes when NSGs suffice and cost less",
    ],
    typicalConnections: ["azure_vnet", "azure_subnet", "azure_vpn_gateway"],
    pricingModel: "Standard: ~$1.25/hour + $0.016/GB. Premium: ~$1.75/hour. Policy: $0.50–$1/policy/month.",
    freeTier: false,
    docUrl: "https://learn.microsoft.com/en-us/azure/firewall/overview",
  },
  {
    id: "azure_bastion",
    name: "Azure Bastion",
    category: "security",
    icon: "🏰",
    shortDescription: "Browser-based RDP/SSH access to VMs — no public IP, no Jump Server required.",
    description:
      "Azure Bastion provides secure, browser-based RDP/SSH to VMs via the Azure Portal over TLS. VMs need no public IP and no exposed SSH/RDP ports. Bastion lives in a dedicated AzureBastionSubnet (/26 or larger) and serves all VMs in the VNet and peered VNets. This eliminates the most common brute-force attack surface (publicly exposed SSH/RDP) without requiring a separately patched jump server.",
    whenToUse: [
      "All production VMs — remove public IPs and exposed SSH/RDP ports entirely",
      "Replacing manually managed jump servers",
      "Regulated environments (PCI, HIPAA) requiring no direct VM internet exposure",
      "Just-in-Time VM access combined with Azure AD Conditional Access",
    ],
    commonMistakes: [
      "Creating the AzureBastionSubnet smaller than /26 — minimum size is required",
      "Keeping NSG rules allowing port 22/3389 from the internet alongside Bastion — remove them",
      "Using Basic SKU then needing Standard features like IP-based connection",
      "Not peering Bastion to spoke VNets — each VNet needs its own Bastion otherwise",
    ],
    typicalConnections: ["azure_vnet", "azure_subnet", "azure_vm"],
    pricingModel: "Basic: ~$0.19/hour. Standard: ~$0.29/hour. Plus outbound data transfer.",
    freeTier: false,
    docUrl: "https://learn.microsoft.com/en-us/azure/bastion/bastion-overview",
  },

  // ── APP SERVICES ──────────────────────────────────────────────────────────────
  {
    id: "azure_service_bus",
    name: "Service Bus",
    category: "appServices",
    icon: "📬",
    shortDescription: "Enterprise message broker with queues and pub/sub topics — guaranteed delivery.",
    description:
      "Azure Service Bus supports queues (point-to-point) and topics with subscriptions (pub/sub). It guarantees at-least-once or at-most-once delivery, FIFO ordering with sessions, dead-lettering, message deferral, and duplicate detection. Premium tier supports VNet integration and Private Endpoints. It is the right choice when you need more reliability and enterprise messaging features than Storage Queues.",
    whenToUse: [
      "Order processing systems requiring exactly-once, ordered processing",
      "Decoupling frontend from backend with guaranteed delivery",
      "Fan-out: one message published to a topic, multiple subscribers consume independently",
      "Long-running workflows with deferred message processing",
    ],
    commonMistakes: [
      "Not configuring a dead-letter queue — poison messages loop forever",
      "Using Service Bus when Storage Queue would suffice — Storage Queues are much cheaper for simple use",
      "Message lock duration expiring before processing completes — causes duplicate delivery",
      "Not using sessions when ordered processing is required",
    ],
    typicalConnections: ["azure_functions", "azure_vm", "azure_aks"],
    pricingModel: "Standard: $0.10/million operations. Premium: ~$677/month/messaging unit.",
    freeTier: false,
    docUrl: "https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-overview",
  },
  {
    id: "azure_event_hub",
    name: "Event Hub",
    category: "appServices",
    icon: "📡",
    shortDescription: "Big data streaming ingestion — millions of events per second from any source.",
    description:
      "Azure Event Hub is a partitioned data streaming platform using a Kafka-compatible consumer model. Multiple consumer groups read the same stream independently. Data is retained for 1–90 days. It is the standard entry point for telemetry, logs, and real-time analytics pipelines feeding Synapse, Databricks, or Stream Analytics. Event Hub Capture automatically writes events to Blob Storage for long-term archiving.",
    whenToUse: [
      "IoT device telemetry ingestion from thousands of devices",
      "Application log and event streaming to a central analytics platform",
      "Real-time fraud detection or anomaly detection pipelines",
      "Kafka-compatible streaming — Event Hub speaks the Kafka protocol",
    ],
    commonMistakes: [
      "Using Event Hub when Service Bus is needed — Event Hub is streaming, not reliable job queuing",
      "Under-partitioning — throughput scales with partition count",
      "Not enabling Event Hub Capture — events older than retention are permanently lost",
      "Ignoring Consumer Group limits — default is 20 per namespace",
    ],
    typicalConnections: ["azure_functions", "azure_synapse", "azure_cosmos_db", "azure_blob_storage"],
    pricingModel: "Basic: $0.028/million events. Standard: $0.028/million + $0.015/TU/hour.",
    freeTier: false,
    docUrl: "https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-about",
  },
  {
    id: "azure_api_management",
    name: "API Management",
    category: "appServices",
    icon: "🚪",
    shortDescription: "Publish, secure, transform, and monitor APIs from a single front-door gateway.",
    description:
      "Azure API Management (APIM) is a fully managed API gateway providing authentication (API keys, OAuth 2.0, JWT), rate limiting, request/response transformation, caching, versioning, and a developer portal. XML-based policies run on every request. The Consumption tier autoscales to zero; Developer is for non-production; Standard and Premium add VNet integration and multi-region deployment.",
    whenToUse: [
      "Exposing multiple backend services as a unified API to external consumers",
      "Enforcing consistent security policies centrally across all APIs",
      "Publishing a developer portal for third-party API consumers",
      "Versioning APIs while maintaining backward compatibility",
    ],
    commonMistakes: [
      "Using APIM as an internal-only microservices router — it adds latency; use an internal gateway",
      "Writing heavy logic in APIM policies — keep policies thin, logic belongs in backends",
      "Not enabling Application Insights — you lose request tracing and latency visibility",
      "Using Developer tier in production — no SLA and it doesn't scale",
    ],
    typicalConnections: ["azure_functions", "azure_app_service", "azure_aks", "azure_application_gateway"],
    pricingModel: "Consumption: $3.50/million calls. Developer: ~$50/month. Standard: ~$780/month.",
    freeTier: false,
    docUrl: "https://learn.microsoft.com/en-us/azure/api-management/api-management-key-concepts",
  },
  {
    id: "azure_openai",
    name: "Azure OpenAI",
    category: "appServices",
    icon: "🤖",
    shortDescription: "GPT-4, embeddings, and DALL-E via Azure — enterprise security and compliance included.",
    description:
      "Azure OpenAI Service provides REST API access to OpenAI's language models (GPT-4o, GPT-4, GPT-3.5-Turbo, Embeddings, DALL-E) hosted within Azure's infrastructure. Unlike direct OpenAI API access, Azure OpenAI supports Private Endpoints (VNet integration), Azure AD authentication, content filtering, and compliance certifications (SOC 2, ISO 27001). Use provisioned throughput units (PTUs) for predictable latency or pay-as-you-go tokens.",
    whenToUse: [
      "Enterprise apps requiring LLM capabilities with data residency and compliance",
      "RAG (Retrieval-Augmented Generation) over private documents using Embeddings",
      "Internal copilots and chatbots connected to company data via Private Endpoints",
      "Code generation and analysis within development toolchains",
    ],
    commonMistakes: [
      "Using the public endpoint in production — use Private Endpoints for VNet-only access",
      "Not setting content filters appropriate to your use case",
      "Verbose system prompts on high-throughput apps — token costs accumulate fast",
      "Not implementing exponential backoff retry — 429 rate limit errors are common under load",
    ],
    typicalConnections: ["azure_app_service", "azure_functions", "azure_aks", "azure_key_vault", "azure_cosmos_db"],
    pricingModel: "GPT-4o: $0.005/1K input tokens, $0.015/1K output. Embeddings: $0.0001/1K tokens.",
    freeTier: false,
    docUrl: "https://learn.microsoft.com/en-us/azure/ai-services/openai/overview",
  },

  // ── MONITORING & OPS ──────────────────────────────────────────────────────────
  {
    id: "azure_monitor",
    name: "Azure Monitor",
    category: "monitoring",
    icon: "📊",
    shortDescription: "Full-stack observability — metrics, logs, alerts, and dashboards for all Azure resources.",
    description:
      "Azure Monitor is the unified monitoring platform for Azure, collecting metrics (93-day retention) and logs from resources, applications, and operating systems. Alerts trigger on metric thresholds, log query results, or Activity Log events and notify via email, SMS, webhook, or Functions. Workbooks provide interactive dashboards. Azure Monitor is the first stop when diagnosing resource health issues or performance degradation.",
    whenToUse: [
      "Setting CPU, memory, and storage alerts on VMs and databases before go-live",
      "Creating dashboards for real-time service health visibility",
      "Querying log data with KQL to diagnose incidents",
      "Triggering auto-scaling actions based on metric thresholds",
    ],
    commonMistakes: [
      "Not configuring Action Groups — alerts fire but nobody is notified",
      "Sending all logs to a single workspace — separate by environment to control costs and access",
      "Short retention without archiving to Storage — violates compliance requirements",
      "Ignoring Azure Advisor recommendations — it surfaces misconfigurations and cost savings",
    ],
    typicalConnections: ["azure_vm", "azure_app_service", "azure_sql_database", "azure_aks", "azure_functions"],
    pricingModel: "Platform metrics: free. Custom metrics: $0.10/metric/month. Logs: $2.76/GB. Alerts: $0.10/month each.",
    freeTier: true,
    docUrl: "https://learn.microsoft.com/en-us/azure/azure-monitor/overview",
  },
  {
    id: "azure_log_analytics",
    name: "Log Analytics",
    category: "monitoring",
    icon: "🔍",
    shortDescription: "Centralised log store — use KQL to search and correlate logs from any Azure source.",
    description:
      "Log Analytics (part of Azure Monitor) is the workspace that stores logs from VMs, containers, Azure resources, and applications. KQL (Kusto Query Language) enables powerful filtering, aggregation, joining, and visualisation. Container Insights feeds AKS logs and metrics here. Workspaces can have different retention periods and access controls per environment. Log Analytics is the foundation for both operational troubleshooting and security detection rules.",
    whenToUse: [
      "Correlating logs from VMs, App Service, and Azure SQL in a single query during incidents",
      "Building security detection rules that alert on suspicious log patterns",
      "Container monitoring: pod logs, node performance, and resource utilisation in AKS",
      "Compliance log retention with separate workspaces per environment",
    ],
    commonMistakes: [
      "One workspace for all environments — costs spiral and access control is impossible",
      "Not learning KQL basics — it's the only way to get value from Log Analytics",
      "Sending verbose debug logs from high-volume apps — ingestion costs accumulate fast",
      "Leaving default 30-day retention when compliance requires longer",
    ],
    typicalConnections: ["azure_monitor", "azure_vm", "azure_aks", "azure_app_service"],
    pricingModel: "$2.76/GB ingested (Pay-As-You-Go). 5GB/month free. Commitment tiers for high volumes.",
    freeTier: true,
    docUrl: "https://learn.microsoft.com/en-us/azure/azure-monitor/logs/log-analytics-overview",
  },
  {
    id: "azure_application_insights",
    name: "Application Insights",
    category: "monitoring",
    icon: "🩻",
    shortDescription: "Application Performance Management — request tracing, exceptions, and dependency calls.",
    description:
      "Application Insights (part of Azure Monitor) instruments your application code to collect request rates, response times, exception details, dependency call traces (SQL, HTTP, Redis), and custom telemetry. The Application Map visualises all service dependencies and shows failure rates. Live Metrics streams real-time telemetry during deployments. Smart Detection automatically surfaces anomalies without explicit threshold rules.",
    whenToUse: [
      "Tracking response time degradation and failure rate spikes in production",
      "Identifying which DB queries or external calls are the latency bottleneck",
      "Distributed tracing across microservices using correlation IDs",
      "User flow and retention analysis for application telemetry",
    ],
    commonMistakes: [
      "High sampling rates on high-traffic services — Application Insights costs scale with ingestion",
      "Hardcoding the instrumentation key in source — use environment variable or Key Vault reference",
      "Ignoring Smart Detection alerts — they catch real anomalies, not just threshold breaches",
      "Not propagating correlation headers across service boundaries — breaks distributed traces",
    ],
    typicalConnections: ["azure_app_service", "azure_functions", "azure_aks", "azure_log_analytics"],
    pricingModel: "5GB/month free. Then $2.76/GB ingested. Sampling reduces volume at cost of trace completeness.",
    freeTier: true,
    docUrl: "https://learn.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview",
  },
];

export function getComponentInfo(id) {
  return AZURE_COMPONENTS.find((c) => c.id === id) ?? null;
}
