export const AZURE_PALETTE = [
  {
    category: "azure_networking",
    label: "Networking",
    components: [
      { type: "azure_vnet",             label: "Virtual Network",     icon: "🌐", cloudType: "Azure VNet" },
      { type: "azure_subnet",           label: "Subnet",              icon: "🔲", cloudType: "Azure Subnet" },
      { type: "azure_nsg",              label: "NSG",                 icon: "🛡️", cloudType: "Network Security Group" },
      { type: "azure_agw",              label: "App Gateway",         icon: "⚡", cloudType: "Application Gateway" },
      { type: "azure_lb",               label: "Load Balancer",       icon: "⚖️", cloudType: "Azure Load Balancer" },
      { type: "azure_frontdoor",        label: "Front Door",          icon: "🚪", cloudType: "Azure Front Door" },
      { type: "azure_dns",              label: "Azure DNS",           icon: "🌏", cloudType: "Azure DNS" },
      { type: "azure_nat_gw",           label: "NAT Gateway",         icon: "🔀", cloudType: "Azure NAT Gateway" },
      { type: "azure_vpn_gateway",      label: "VPN Gateway",         icon: "🔒", cloudType: "VPN Gateway" },
      { type: "azure_expressroute",     label: "ExpressRoute",        icon: "🔌", cloudType: "ExpressRoute" },
      { type: "azure_traffic_mgr",      label: "Traffic Manager",     icon: "🚦", cloudType: "Traffic Manager" },
      { type: "azure_bastion",          label: "Azure Bastion",       icon: "🏰", cloudType: "Azure Bastion" },
      { type: "azure_private_endpoint", label: "Private Endpoint",    icon: "🎯", cloudType: "Private Endpoint" },
      { type: "azure_firewall",         label: "Azure Firewall",      icon: "🔥", cloudType: "Azure Firewall" },
      { type: "azure_ddos",             label: "DDoS Protection",     icon: "🛡️", cloudType: "DDoS Protection" },
    ],
  },
  {
    category: "azure_compute",
    label: "Compute",
    components: [
      { type: "azure_vm",              label: "Virtual Machine",   icon: "🖥️", cloudType: "Azure VM" },
      { type: "azure_vmss",            label: "VM Scale Set",      icon: "⚖️", cloudType: "VMSS" },
      { type: "azure_aks",             label: "AKS",               icon: "☸️", cloudType: "AKS" },
      { type: "azure_functions",       label: "Functions",         icon: "λ",  cloudType: "Azure Functions" },
      { type: "azure_aci",             label: "Container Instance",icon: "🐳", cloudType: "ACI" },
      { type: "azure_app_service",     label: "App Service",       icon: "📱", cloudType: "App Service" },
      { type: "azure_container_apps",  label: "Container Apps",    icon: "📦", cloudType: "Container Apps" },
      { type: "azure_batch",           label: "Azure Batch",       icon: "🔢", cloudType: "Azure Batch" },
      { type: "azure_spring_apps",     label: "Spring Apps",       icon: "🌱", cloudType: "Azure Spring Apps" },
      { type: "azure_static_web",      label: "Static Web Apps",   icon: "📄", cloudType: "Static Web Apps" },
      { type: "azure_acr",             label: "Container Registry",icon: "🗂️", cloudType: "Azure Container Registry" },
    ],
  },
  {
    category: "azure_storage",
    label: "Storage",
    components: [
      { type: "azure_blob",     label: "Blob Storage",      icon: "🪣", cloudType: "Azure Blob" },
      { type: "azure_files",    label: "Azure Files",       icon: "📁", cloudType: "Azure Files" },
      { type: "azure_disk",     label: "Managed Disk",      icon: "💾", cloudType: "Managed Disk" },
      { type: "azure_table",    label: "Table Storage",     icon: "📋", cloudType: "Azure Table Storage" },
      { type: "azure_queue",    label: "Queue Storage",     icon: "📬", cloudType: "Azure Queue Storage" },
      { type: "azure_datalake", label: "Data Lake Gen2",    icon: "💧", cloudType: "Azure Data Lake Storage Gen2" },
      { type: "azure_backup",   label: "Azure Backup",      icon: "🔄", cloudType: "Azure Backup" },
    ],
  },
  {
    category: "azure_database",
    label: "Database",
    components: [
      { type: "azure_sql",               label: "Azure SQL",          icon: "🗄️", cloudType: "Azure SQL Database" },
      { type: "azure_cosmosdb",          label: "Cosmos DB",          icon: "🌌", cloudType: "Cosmos DB" },
      { type: "azure_redis",             label: "Redis Cache",        icon: "🚀", cloudType: "Azure Redis" },
      { type: "azure_postgres",          label: "PostgreSQL",         icon: "🐘", cloudType: "Azure DB for PostgreSQL" },
      { type: "azure_mysql",             label: "MySQL",              icon: "🐬", cloudType: "Azure DB for MySQL" },
      { type: "azure_mariadb",           label: "MariaDB",            icon: "🐬", cloudType: "Azure DB for MariaDB" },
      { type: "azure_synapse",           label: "Synapse Analytics",  icon: "📊", cloudType: "Azure Synapse Analytics" },
      { type: "azure_managed_instance",  label: "SQL Managed Instance",icon: "🗃️",cloudType: "SQL Managed Instance" },
    ],
  },
  {
    category: "azure_security",
    label: "Security",
    components: [
      { type: "azure_keyvault",    label: "Key Vault",          icon: "🔐", cloudType: "Key Vault" },
      { type: "azure_aad",         label: "Azure AD / Entra ID",icon: "👤", cloudType: "Azure Active Directory" },
      { type: "azure_waf",         label: "WAF Policy",         icon: "🔒", cloudType: "WAF Policy" },
      { type: "azure_defender",    label: "Defender for Cloud", icon: "🛡️", cloudType: "Microsoft Defender for Cloud" },
      { type: "azure_sentinel",    label: "Microsoft Sentinel", icon: "👁️", cloudType: "Microsoft Sentinel" },
      { type: "azure_managed_id",  label: "Managed Identity",   icon: "🔑", cloudType: "Managed Identity" },
      { type: "azure_policy",      label: "Azure Policy",       icon: "📋", cloudType: "Azure Policy" },
    ],
  },
  {
    category: "azure_integration",
    label: "Integration",
    components: [
      { type: "azure_servicebus",    label: "Service Bus",      icon: "📣", cloudType: "Service Bus" },
      { type: "azure_eventhub",      label: "Event Hub",        icon: "🌊", cloudType: "Event Hub" },
      { type: "azure_logicapp",      label: "Logic App",        icon: "🔄", cloudType: "Logic App" },
      { type: "azure_apim",          label: "API Management",   icon: "🚪", cloudType: "API Management" },
      { type: "azure_signalr",       label: "SignalR Service",  icon: "📡", cloudType: "SignalR Service" },
      { type: "azure_notification_hub", label: "Notification Hub", icon: "🔔", cloudType: "Notification Hub" },
    ],
  },
  {
    category: "azure_analytics",
    label: "Analytics",
    components: [
      { type: "azure_datafactory",       label: "Data Factory",        icon: "🏭", cloudType: "Azure Data Factory" },
      { type: "azure_stream_analytics",  label: "Stream Analytics",    icon: "🌊", cloudType: "Stream Analytics" },
      { type: "azure_databricks",        label: "Azure Databricks",    icon: "✨", cloudType: "Azure Databricks" },
      { type: "azure_hdinsight",         label: "HDInsight",           icon: "⚡", cloudType: "HDInsight" },
      { type: "azure_purview",           label: "Microsoft Purview",   icon: "🔭", cloudType: "Microsoft Purview" },
    ],
  },
  {
    category: "azure_ai",
    label: "AI / ML",
    components: [
      { type: "azure_openai",    label: "Azure OpenAI",        icon: "🤖", cloudType: "Azure OpenAI Service" },
      { type: "azure_cognitive", label: "Cognitive Services",  icon: "🧠", cloudType: "Azure Cognitive Services" },
      { type: "azure_ml",        label: "Machine Learning",    icon: "🔬", cloudType: "Azure Machine Learning" },
      { type: "azure_bot",       label: "Bot Service",         icon: "💬", cloudType: "Azure Bot Service" },
      { type: "azure_search",    label: "AI Search",           icon: "🔍", cloudType: "Azure AI Search" },
    ],
  },
  {
    category: "azure_monitoring",
    label: "Monitoring",
    components: [
      { type: "azure_monitor",        label: "Azure Monitor",         icon: "📊", cloudType: "Azure Monitor" },
      { type: "azure_app_insights",   label: "Application Insights",  icon: "🔍", cloudType: "Application Insights" },
      { type: "azure_log_analytics",  label: "Log Analytics",         icon: "📝", cloudType: "Log Analytics Workspace" },
    ],
  },
  {
    category: "azure_devops",
    label: "DevOps",
    components: [
      { type: "azure_devops",   label: "Azure DevOps",       icon: "🔄", cloudType: "Azure DevOps" },
    ],
  },
];
