export const GCP_PALETTE = [
  {
    category: "gcp_networking",
    label: "Networking",
    components: [
      { type: "gcp_vpc",                   label: "VPC Network",           icon: "🌐", cloudType: "GCP VPC" },
      { type: "gcp_subnet",                label: "Subnetwork",            icon: "🔲", cloudType: "GCP Subnet" },
      { type: "gcp_firewall",              label: "Firewall Rule",         icon: "🛡️", cloudType: "Firewall Rule" },
      { type: "gcp_lb",                    label: "Cloud Load Balancing",  icon: "⚖️", cloudType: "Cloud LB" },
      { type: "gcp_cdn",                   label: "Cloud CDN",             icon: "☁️", cloudType: "Cloud CDN" },
      { type: "gcp_dns",                   label: "Cloud DNS",             icon: "🌏", cloudType: "Cloud DNS" },
      { type: "gcp_nat",                   label: "Cloud NAT",             icon: "🔀", cloudType: "Cloud NAT" },
      { type: "gcp_vpn",                   label: "Cloud VPN",             icon: "🔒", cloudType: "Cloud VPN" },
      { type: "gcp_interconnect",          label: "Cloud Interconnect",    icon: "🔌", cloudType: "Cloud Interconnect" },
      { type: "gcp_private_sc",            label: "Private Service Connect",icon: "🎯", cloudType: "Private Service Connect" },
      { type: "gcp_network_endpoint_grp",  label: "Network Endpoint Group",icon: "🔗", cloudType: "NEG" },
    ],
  },
  {
    category: "gcp_compute",
    label: "Compute",
    components: [
      { type: "gcp_gce",             label: "Compute Engine",         icon: "🖥️", cloudType: "GCE VM" },
      { type: "gcp_mig",             label: "Managed Instance Group", icon: "⚖️", cloudType: "MIG" },
      { type: "gcp_gke",             label: "GKE",                    icon: "☸️", cloudType: "Google Kubernetes Engine" },
      { type: "gcp_cloud_run",       label: "Cloud Run",              icon: "🏃", cloudType: "Cloud Run" },
      { type: "gcp_cloud_functions", label: "Cloud Functions",        icon: "λ",  cloudType: "Cloud Functions" },
      { type: "gcp_app_engine",      label: "App Engine",             icon: "📱", cloudType: "App Engine" },
      { type: "gcp_cloud_batch",     label: "Cloud Batch",            icon: "🔢", cloudType: "Cloud Batch" },
      { type: "gcp_cloud_composer",  label: "Cloud Composer",         icon: "🎼", cloudType: "Cloud Composer (Airflow)" },
    ],
  },
  {
    category: "gcp_storage",
    label: "Storage",
    components: [
      { type: "gcp_gcs",             label: "Cloud Storage",     icon: "🪣", cloudType: "GCS Bucket" },
      { type: "gcp_filestore",       label: "Filestore",         icon: "📁", cloudType: "Filestore" },
      { type: "gcp_persistent_disk", label: "Persistent Disk",   icon: "💾", cloudType: "Persistent Disk" },
      { type: "gcp_backup",          label: "Backup and DR",     icon: "🔄", cloudType: "Google Cloud Backup and DR" },
    ],
  },
  {
    category: "gcp_database",
    label: "Database",
    components: [
      { type: "gcp_cloudsql",    label: "Cloud SQL",      icon: "🗄️", cloudType: "Cloud SQL" },
      { type: "gcp_alloydb",     label: "AlloyDB",        icon: "⚡", cloudType: "AlloyDB for PostgreSQL" },
      { type: "gcp_spanner",     label: "Cloud Spanner",  icon: "🌌", cloudType: "Cloud Spanner" },
      { type: "gcp_firestore",   label: "Firestore",      icon: "🔥", cloudType: "Firestore" },
      { type: "gcp_bigtable",    label: "Bigtable",       icon: "📊", cloudType: "Cloud Bigtable" },
      { type: "gcp_memorystore", label: "Memorystore",    icon: "🚀", cloudType: "Memorystore (Redis)" },
      { type: "gcp_datastore",   label: "Datastore",      icon: "🗃️", cloudType: "Cloud Datastore" },
    ],
  },
  {
    category: "gcp_security",
    label: "Security & Identity",
    components: [
      { type: "gcp_iam",                   label: "IAM",                    icon: "🔑", cloudType: "GCP IAM" },
      { type: "gcp_secret_manager",        label: "Secret Manager",         icon: "🔐", cloudType: "Secret Manager" },
      { type: "gcp_armor",                 label: "Cloud Armor",            icon: "🔒", cloudType: "Cloud Armor" },
      { type: "gcp_kms",                   label: "Cloud KMS",              icon: "🗝️", cloudType: "Cloud Key Management Service" },
      { type: "gcp_certificate_manager",   label: "Certificate Manager",    icon: "📜", cloudType: "Certificate Manager" },
      { type: "gcp_scc",                   label: "Security Command Center",icon: "🛡️", cloudType: "Security Command Center" },
    ],
  },
  {
    category: "gcp_integration",
    label: "Integration",
    components: [
      { type: "gcp_pubsub",       label: "Pub/Sub",          icon: "📣", cloudType: "Cloud Pub/Sub" },
      { type: "gcp_dataflow",     label: "Dataflow",         icon: "🌊", cloudType: "Cloud Dataflow" },
      { type: "gcp_apigee",       label: "Apigee",           icon: "🚪", cloudType: "Apigee API Management" },
      { type: "gcp_tasks",        label: "Cloud Tasks",      icon: "📋", cloudType: "Cloud Tasks" },
      { type: "gcp_scheduler",    label: "Cloud Scheduler",  icon: "⏰", cloudType: "Cloud Scheduler" },
      { type: "gcp_workflows",    label: "Cloud Workflows",  icon: "🔄", cloudType: "Cloud Workflows" },
    ],
  },
  {
    category: "gcp_analytics",
    label: "Analytics",
    components: [
      { type: "gcp_bigquery",      label: "BigQuery",            icon: "📈", cloudType: "BigQuery" },
      { type: "gcp_dataproc",      label: "Dataproc",            icon: "⚡", cloudType: "Cloud Dataproc" },
      { type: "gcp_looker",        label: "Looker",              icon: "🔭", cloudType: "Looker" },
      { type: "gcp_data_catalog",  label: "Data Catalog",        icon: "📂", cloudType: "Data Catalog" },
      { type: "gcp_analytics_hub", label: "Analytics Hub",       icon: "🏪", cloudType: "Analytics Hub" },
    ],
  },
  {
    category: "gcp_ai",
    label: "AI / ML",
    components: [
      { type: "gcp_vertex_ai",    label: "Vertex AI",            icon: "🤖", cloudType: "Vertex AI" },
      { type: "gcp_automl",       label: "AutoML",               icon: "✨", cloudType: "AutoML" },
      { type: "gcp_vision_ai",    label: "Vision AI",            icon: "👁️", cloudType: "Cloud Vision API" },
      { type: "gcp_speech",       label: "Speech-to-Text",       icon: "🎙️", cloudType: "Speech-to-Text" },
      { type: "gcp_translation",  label: "Cloud Translation",    icon: "🌍", cloudType: "Cloud Translation API" },
      { type: "gcp_natural_lang", label: "Natural Language",     icon: "📝", cloudType: "Cloud Natural Language API" },
    ],
  },
  {
    category: "gcp_monitoring",
    label: "Monitoring",
    components: [
      { type: "gcp_monitoring",        label: "Cloud Monitoring", icon: "📊", cloudType: "Cloud Monitoring" },
      { type: "gcp_logging",           label: "Cloud Logging",    icon: "📝", cloudType: "Cloud Logging" },
      { type: "gcp_trace",             label: "Cloud Trace",      icon: "🔍", cloudType: "Cloud Trace" },
      { type: "gcp_error_reporting",   label: "Error Reporting",  icon: "⚠️", cloudType: "Error Reporting" },
    ],
  },
  {
    category: "gcp_devops",
    label: "DevOps",
    components: [
      { type: "gcp_cloud_build",        label: "Cloud Build",        icon: "🔨", cloudType: "Cloud Build" },
      { type: "gcp_cloud_deploy",       label: "Cloud Deploy",       icon: "🚀", cloudType: "Cloud Deploy" },
      { type: "gcp_artifact_registry",  label: "Artifact Registry",  icon: "🗂️", cloudType: "Artifact Registry" },
      { type: "gcp_source_repo",        label: "Source Repositories",icon: "📦", cloudType: "Cloud Source Repositories" },
    ],
  },
];
